### ISSUE TITLE
Webサイトの移設について

### ISSUE THREAD

**Issue by matchy256** [nseg-jp/committee#1]
現在のサイトを運営していただいているhATrayfloodさんから、今後も PukiWiki で運用を続けるのは問題があるかもという意見が出る。

サーバーホスティングもhATrayfloodさんに頼りきりなので、そこも含めてどうすれば良いか考えたい

**Comment by matchy256** [comment]
GitHubPage にしてしまえばどうかと思って、だったら全体を一部で話題のJekyllでやればいいんじゃないかなーと思ってやってみた。
https://github.com/nseg-jp/nseg-test.github.com

けど、思いの外面倒くさい。

Wiki に関してはGitHubのWikiをそのまま使って、NSEG の紹介的な固定ページを Jekyll で作るということにしてはどうだろうか。ご意見募集

**Comment by hATrayflood** [comment]
pukiwikiで問題なのは、過去数年にわたってアップデートがないこと。漏れて困るようなデータは一切ないが、バグを突かれてサーバを悪用させられるリスクは少なからずある。
安全に使えるwikiエンジンへの乗り換えを検討したい。機能的には現行wiki程度で問題ないが、賢いスパム避けがあるとありがたい。

github pageとgithub wikiを連携して使う案に関しては、レイアウトがあまり融通の利かないgithub wikiが足を引っ張る気がする。
どちらかに統一したほうがいいのでは。

**Comment by matchy256** [comment]
Wikiに関してはGitHubのWikiに統一かなと。
で、せっかく nseg.jp ドメインがあって、それを GitHub Wiki に直接割り当てることはできないので、Wiki とは別に NSEG の表玄関的なサイト (Wiki にリンクしているだけ？) を GitHub Page で作ればいいのかなーと思いました

**Comment by hATrayflood** [comment]
となると、全面iframeなgithub pageを用意して、常にwikiをそのまま表示させるみたいな感じすかね。いっそのこと

**Comment by matchy256** [comment]
うーん、それも味気ないというか、せっかくならJekyllでそれなりにあそびたい気もするので「NSEGとは？」とか「参加方法」みたいな、あまり更新されないような呼び水的コンテンツをおいといても良いような気もするのですが

**Comment by matchy256** [comment]
ちょっと試作してみた
http://nseg-jp.github.io/

**Comment by matchy256** [comment]
GitHub Wiki も画像とかを添付する画面なくなっちゃったんですね。今のWikiもほとんど添付とかしないけど、不便ですかね？個人的にはgitで添付できれば充分な気がしますが

http://elim.github.io/tech/2013/06/28/upload-image-to-your-github-wiki-page/

**Comment by tmtm** [comment]
おお、 http://nseg-jp.github.io/ カッコいいですね。いいと思います。

**Comment by matchy256** [comment]
どもども。ちなみにトップのスライドショーはFlickrから「nseg」タグがついているものを引っ張りだしてランダム表示しています。

で、今日ほぼまる１日かけて現 Wiki のデータを GitHub に移して変な所を修正しました。
https://github.com/nseg-jp/nseg-jp.github.com/wiki

ちょっとこの状態でみてもらって、いけそうかどうか判断したいですね

**Comment by hATrayflood** [comment]
よさげですね。トップページいいです。
wikiページ移植ありがとうございます。

**Comment by matchy256** [comment]
Organization ページ用のプロジェクト (名称固定) だと Wiki の URI がやたら長いので、nseg-jp.github.com → w (「www」の「w」) に変えてみました。

**次期nseg.jp**  http://nseg-jp.github.io/w/ (http://nseg.jp/ になる予定)

**Wiki**  https://github.com/nseg-jp/w/wiki/

**Comment by matchy256** [comment]
ひととおり見てみて問題点的なことを。個人的には些細な問題という認識ですが。

まず、PukiWiki の投票プラグインを使っていた部分は勝手ながらばっさり削除しています。

過去記事でいうと遠距離クルマ乗り合いのデカイ表が厳しいですね。こことかの。  
https://github.com/nseg-jp/w/wiki/%E7%AC%AC24%E5%9B%9E%E5%8B%89%E5%BC%B7%E4%BC%9A

上にも書きましたが、ファイル添付を git 経由でやらないとイカンあたりがメンドイ人にはメンドイでしょうか。

Wiki および Web サイトの編集方法について書き起こしてみました。  
https://github.com/nseg-jp/w/wiki/Web%E3%82%B5%E3%82%A4%E3%83%88%E3%81%AE%E6%9B%B4%E6%96%B0%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6

ご意見募集

**Comment by matchy256** [comment]
それから、トップページに「NSEGとは」を書くにあたり、当初あったように「だれでも NSEG の名前で勉強会やっておｋ」と改めて書いてみて、まったく勝手にやってやりっ放しというのもいろいろツラいなと思いました。

で、やったら Wiki に記録つけてねという文言を勝手に追加してみました。ワタシが思いつきで書いたものなので、ML あたりで承認を得る必要があるかもですね。

**Comment by hATrayflood** [comment]
車の乗り合わせとかはむしろ「wikiでやるなよ」的な感じがあるのと、残しておく意味もあんまりないので消してもいいと思います。(wikiに書き出したの僕ですが)

ファイル添付はめったにないので特に問題ないかと。

**Comment by matchy256** [comment]
消すのもメンドいので残しておきます。次から見づらかったら違う手段を考えるということで。

あとこれどうやって進めよう？ML でこんなんできたけどどう？問題あったらいついつまでにちょうだい的な展開で良いかなー？

**Comment by matchy256** [comment]
というわけでMLにご意見もとめてみた

**Comment by stealthinu** [comment]
matchyさん、手で移されたの、大変お疲れ様でした。
いい感じに思えます。

今９人しか登録されてるメンバーいないから、ここを増やさないとな、と感じました。

2014-06-24 21:20 GMT+09:00 MACHIDA Hideki notifications@github.com:

> というわけでMLにご意見もとめてみた
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nseg-jp/committee/issues/1#issuecomment-46963720.

## 

佐藤 潔 (Kiyoshi SATOH) satoh@hakuba.jp
有限会社 ジーワークス Tel:090-5513-3039
http://www.hakuba.jp/gworks/

**Comment by matchy256** [comment]
どもども。いちおーここのスクリプトを使わせていただいて全体ざっくりとは変換しているのですけど、結局表とかは手で直さないとダメでした
http://voidptr.seesaa.net/article/391400114.html

**Comment by matchy256** [comment]
次の勉強会が終わって現Wiki更新がおちついたところで、「いよいよ移行しませんか？」と投げかけてみますかね

**Comment by tatsumi33** [comment]
ここで議論されていたのですね。私も登録してもらえるとうれしいです。
サイトがあまりに美しくなっていてどこかのWeb系ベンチャー企業のページかと思いました。ただモバイルで見ると写真のロードが厳しい感じもします。

**Comment by matchy256** [comment]
どもども。メンバーにいれさせていただきました。もしよければこちらのページでPublicメンバーに設定してもらえると嬉しいです。
https://github.com/orgs/nseg-jp/members

本当は Web デザインスキルとかアピールしたい方に作ってもらうといいんですけどねー。今までそういうハナシ出なかったのならまあ呼びかけても出ないかなと思って勝手に暴走してみました。
で、画像ですが、やっぱ重いですかね。Flick のいちばん解像度高いヤツを引っ張りだしているのですが、どうせオーバーレイかけて顔とか見づらくしているので、もちょっと解像度下げてもいいのかなとは思っていました。
スマホを意識して320pxにしてみました。PCでも顔を判別しにくいぐらいになってちょうどいいかな？？

**Comment by tatsumi33** [comment]
登録ありがとうございます。写真も違和感ないと思います。私はこれくらいかなと思いますが、他の方のご意見もあわせて調整した方がいいかもしれません。
しかし matchy2 さんがここまでデキル人だとは思っていませんでした。ただの自転車パンク修理屋さんではなかったんですね。やりたい人がやるのが一番だと思うのでこれでいいと思います。

**Comment by matchy256** [comment]
地味に傷つくわｗｗｗｗｗ＞ただの自転車パンク修理屋さんではなかった

まあいろいろと転がっていたのを組み合わせただけで、難しいことはなんもしてないんすけどね。  
で、自分で作っちゃうと「反対意見がないのでこれで承認とします」と言いづらいのも事実なので、ある程度たってからそんなような動議をMLの方に出してみようかなと。  他のどなかに出していただけるとワタシ的にはもっといいのですが。

てゆーかこんなん全然ダメだからオレに作らせろーでもいいので、なんか反応してほしいというか…(汗

**Comment by matchy256** [comment]
7/27 の NSEG 勉強会で極簡単にこれまでの経緯と現状を説明させていただきます。
スライドはこれを使う予定→ http://rawgit.com/matchy2/revealjs/master/nsegnewweb.htm

こんなんダメだ！という意見を出すなら今のうちということでｗ

**Comment by hATrayflood** [comment]
あ、あれ？404。。。

**Comment by matchy256** [comment]
すんまそん、リンク失敗した。これね
http://rawgit.com/matchy2/revealjs/master/nsegnewweb.html

**Comment by matchy256** [comment]
そういえばこのチケット閉じるの忘れてた(汗。
移設完了しているのでクローズします
